### PR TITLE
Version 2.2.0

### PR DESCRIPTION
**Pull request by rohit01**
Making loglevel configurable for version 2.2.0.

Please update recreate tag 2.2.0 from this branch.

### CODE REVIEW

**Comment by rohit01** [comment]
Don't merge this on master. This is a PR for version 2.2.0 tag. There is no branch to raise the PR.

Request to recreate tag after pulling code from this branch, so that loglevel parameter is configurable.

**Comment by bobrik** [comment]
The easiest way to achieve what you want is to build your own image with whatever config you want on top of this one. You can `COPY` the whole config or just `RUN` sed.

**Comment by rohit01** [comment]
@bobrik Yes, I have done that: https://hub.docker.com/r/rohit01/opentsdb/. I am running this in prod at present.

I like your project and it would be great, if it is part of source (cloudflare/opentsdb) project itself. In that way, it's easy to get features contributed by everybody at one place. Custome log-level is a very basic requirement if someone is using it at scale (like me).

**Comment by bobrik** [comment]
I'll look into it when the next release of OpenTSDB come out.

**Pull request closed without merging**
